; TFLite Micro hello_world sample - sine wave inference on nRF54LM20A
; GCC 14.2.1 (toolchain-gccarmnoneeabi@1.140201.0) — enables CMSIS-NN (__sxtb16 builtin)
[env:seeed-xiao-nrf54lm20a-npu]
platform = file:///home/seeed/workspace/nrf54lm20a_pio/platform-seeedboards
framework = zephyr
board = seeed-xiao-nrf54lm20a-npu
monitor_speed = 115200
platform_packages = platformio/toolchain-gccarmnoneeabi@1.140201.0
