; Edge AI Regression Sample for XIAO nRF54LM20B
; Air quality prediction using gas sensor data

[env:seeed-xiao-nrf54lm20a-npu]
platform = file:///home/seeed/workspace/nrf54lm20a_pio/platform-seeedboards
framework = zephyr
board = seeed-xiao-nrf54lm20a-npu
monitor_speed = 115200
board_build.edge_ai = true
