; XIAO STM32C5 CAN FD data phase stress test, PSIS/system clock = 100 MHz
; FDCAN2: PB5 RX / PB13 TX, CAN_STB: PB14

[env:seeed-xiao-stm32c5]
platform = https://github.com/cumin777/platform-seeedboards.git#add_xiao_c5_support
framework = zephyr
board = seeed-xiao-stm32c5
monitor_speed = 115200
platform_packages = framework-zephyr@~3.40400.0
