; PlatformIO Project Configuration File
;
; nPM1300 register read for XIAO nRF54LM20B.

[env:seeed-xiao-nrf54lm20b]
platform = https://github.com/cumin777/platform-seeedboards.git#add-nrf54lm20b-samples
framework = zephyr
board = seeed-xiao-nrf54lm20b
monitor_speed = 115200
