; XIAO STM32C5 USB CDC ACM Echo Demo
; USB-C PA11/PA12 are USB FS DM/DP. Open the host CDC COM port at 1,000,000 bps.

[env:seeed-xiao-stm32c5]
platform = https://github.com/cumin777/platform-seeedboards.git#add_xiao_c5_support
framework = zephyr
board = seeed-xiao-stm32c5
monitor_speed = 1000000
platform_packages = framework-zephyr@~3.40400.0
