; TFLite Micro mnist_lstm sample — LSTM digit recognition (10 embedded MNIST
; samples). GCC 14.2.1 + CMSIS-NN.
[env:seeed-xiao-nrf54lm20a-npu]
platform = file:///home/seeed/workspace/nrf54lm20a_pio/platform-seeedboards
framework = zephyr
board = seeed-xiao-nrf54lm20a-npu
monitor_speed = 115200
platform_packages = platformio/toolchain-gccarmnoneeabi@1.140201.0
