; XIAO nRF54LM20B Edge AI gesture data collection sample.
[env:seeed-xiao-nrf54lm20b]
platform = https://github.com/cumin777/platform-seeedboards.git#add-nrf54lm20b-samples
framework = zephyr
board = seeed-xiao-nrf54lm20b
monitor_speed = 115200
