; NUCLEO C5A3ZG GPIO Demo
; D0 (PA0) output toggle, D1 (PA1) input read

[env:nucleo_c5a3zg]
platform = https://github.com/cumin777/platform-seeedboards.git#add_xiao_c5_support
framework = zephyr
board = seeed-xiao-stm32c5
monitor_speed = 115200
platform_packages = framework-zephyr@~3.40400.0
