; XIAO STM32C5 DHT20 continuous read sample
; Uses I2C1 (PB6 SCL / PB7 SDA) at 400 kHz.

[env:seeed-xiao-stm32c5]
platform = https://github.com/cumin777/platform-seeedboards.git#add_xiao_c5_support
framework = zephyr
board = seeed-xiao-stm32c5
monitor_speed = 115200
platform_packages = framework-zephyr@~3.40400.0
