; PlatformIO Project Configuration File
;
; XIAO STM32C5 onboard IMU temperature PID + 6-axis interrupt sample.

[env:seeed-xiao-stm32c5]
platform = https://github.com/cumin777/platform-seeedboards.git#add_xiao_c5_support
framework = zephyr
board = seeed-xiao-stm32c5
monitor_speed = 115200
platform_packages = framework-zephyr@~3.40400.0
