; Copyright (c) 2026 Seeed Technology Co., Ltd.
; SPDX-License-Identifier: Apache-2.0

[env:seeed-xiao-nrf54lm20a-npu]
platform = file:///home/seeed/workspace/nrf54lm20a_pio/platform-seeedboards
framework = zephyr
board = seeed-xiao-nrf54lm20a-npu
monitor_speed = 115200
