; PlatformIO Project Configuration File
;
; nPM1300 register read and LED1 charge indicator demo for XIAO nRF54LM20A.

[env:seeed-xiao-nrf54lm20a]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
framework = zephyr
board = seeed-xiao-nrf54lm20a
monitor_speed = 115200
