; PlatformIO Project Configuration File
;
; XIAO STM32C5 Zephyr Blinky Example
; UF2 bootloader: app starts at 0x08008000

[env:seeed-xiao-stm32c5]
platform = /mnt/d/workspace/platform-seeedboards
framework = zephyr
board = seeed-xiao-stm32c5
monitor_speed = 115200
platform_packages = framework-zephyr@~3.40400.0
