; Edge AI Anomaly Detection Sample for XIAO nRF54LM20B
; Mechanical gear anomaly detection using vibration analysis (Neuton only)

[env:seeed-xiao-nrf54lm20a-npu]
platform = file:///home/seeed/workspace/nrf54lm20a_pio/platform-seeedboards
framework = zephyr
board = seeed-xiao-nrf54lm20a-npu
monitor_speed = 115200
board_build.edge_ai = true
