[env:seeed-xiao-esp32-s3-sense]
platform = https://github.com/cumin777/platform-seeedboards.git#add_xiao_c5_support
framework = arduino
board = seeed-xiao-esp32-s3-sense
monitor_speed = 115200
build_flags = -DNR_OF_LEDS=1
