; PlatformIO Project Configuration File
;
; XIAO STM32C5 Zephyr crystal MCO output test.
; Outputs LSE on MCO1/PH2-BOOT0 and HSE on MCO2/PA9-D6.

[env:seeed-xiao-stm32c5]
platform = https://github.com/cumin777/platform-seeedboards.git#add_xiao_c5_support
framework = zephyr
board = seeed-xiao-stm32c5
platform_packages = framework-zephyr@~3.40400.0
