; XIAO STM32C5 BOOT button example
; PH2/BOOT0 is used as a normal user button while the application runs.

[env:seeed-xiao-stm32c5]
platform = https://github.com/cumin777/platform-seeedboards.git#fix/xiao-nrf54lm20a-buck2-always-on
framework = zephyr
board = seeed-xiao-stm32c5
monitor_speed = 115200
platform_packages = framework-zephyr@~3.40400.0
