; XIAO STM32C5 BOOT button example
; PH2/BOOT0 is used as a normal user button while the application runs.

[env:seeed-xiao-stm32c5]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
framework = zephyr
board = seeed-xiao-stm32c5
monitor_speed = 115200
platform_packages = framework-zephyr@~3.40400.0
